### ISSUE TITLE
Unable to find an entry point named 'enet_address_set_host' in DLL 'enet'.

### ISSUE THREAD

**Issue by nurbat** [SoftwareGuy/ENet-CSharp#9] opened 2019-12-13 18:54 UTC
Unable to find an entry point named 'enet_address_set_host' in DLL 'enet'.

**Comment by SoftwareGuy** [comment] 2019-12-14 01:42
1. I need more information.
- What is your build target? NET Core? NET Standard? NET Framework?
- What is your build platform? x86_32, x86_64, ARM, ARM64?

2. How can I reproduce this?
- I need a code sample.

**Comment by nurbat** [comment] 2019-12-14 13:01
What is your build target? **NET Core**
**x86_32, x86_64**
https://github.com/SoftwareGuy/Ignorance/blob/master/Assets/Mirror/Runtime/Transport/Ignorance/IgnoranceThreaded.cs
: 372
![изображение](https://user-images.githubusercontent.com/5789051/70849089-9f92c800-1e82-11ea-8097-1e88a490671e.png)

**Comment by SoftwareGuy** [comment] 2019-12-21 07:46
Sorry for the delay.

I'll look into this. `enet_address_set_host` does definitely exist in there, I swear it does.

**Comment by SoftwareGuy** [comment] 2020-01-07 03:02
enet_address_set_host exists here in `enet.h`:
https://github.com/SoftwareGuy/ENet-CSharp/blob/fc61ba33205a54d77cf8c87fbf426587099c4303/Source/Native/enet.h#L792
...and...
https://github.com/SoftwareGuy/ENet-CSharp/blob/fc61ba33205a54d77cf8c87fbf426587099c4303/Source/Native/enet.h#L4419

Going to close this. Open it again if you've built from my repo, this looks like you might have grabbed a binary from NX's repo or something. I can compile and test this with no errors.

EDIT: Ignorance also uses SetHost too, and it had no problems.

**Closed as completed** 2020-01-07 03:02 UTC
Labels: bug, question
