### ISSUE TITLE
UWP Support?

### ISSUE THREAD

**Issue by Alexees** [SoftwareGuy/ENet-CSharp#8] opened 2019-11-12 15:38 UTC
Did not know where to ask so I ask here.
I'd like to use Dissonance across the board but UWP is missing and so I'm stuck with Telepathy, which is not the brightest idea.
I was told by Dissonancees that I should use Ignorance for UDP transport, which is using ENET under the hood. Would it be hard to port it to UWP?
With Hololens 2 in the making it would be great to have it for x32 (HL1), x64(desktop) and ARM64 (HL2)

**Comment by SoftwareGuy** [comment] 2019-11-13 01:28
Excellent question.

Out of the box, ENET is not compatible with UWP. However, I would have to look into this and do some R&D on the matter. Looking at some google posts UWP is one of those oddball platforms and I'm getting mixed research of "Yes it is possible natively" and "No, you'd need to make a wrapper that is dedicated for UWP".

Even if we did make it work for UWP... trying to get it working in Unity would probably be a bitch, unless it decided to play ball and slide on like a glove. 

And yes, using VoIP with TCP is not always the best idea - it could work *somewhat* (Mumble used TCP as fallback when UDP failed) but you'd probably lag the server a lot if your voice clients are dropping packets.

Let me look into this and I'll get back to you. 🙂

**Comment by Alexees** [comment] 2019-11-13 06:22
That would be awesome and a total life saver.
At least Martin Evans from Dissonance also predicted it being rather easy to compile for UWP.
And there is probably some potential in promoting it further with HL2, right? 😜

**Comment by Alexees** [comment] 2019-11-22 11:22
@SoftwareGuy hi again, did you find the time to look into this?

**Comment by SoftwareGuy** [comment] 2019-11-23 01:26
I looked into it for like 10 minutes and then it got flooded downstream with a lot of other things.
I'm installing UWP stuff now for Visual Studio and going to see if this'll work.

**Comment by SoftwareGuy** [comment] 2019-11-23 02:35
Alright, seems like this *might* work. I used a UWP C# Console Application and a very simple initialization routine. This is the result:

![image](https://user-images.githubusercontent.com/1762115/69471665-82bc2500-0ded-11ea-90cd-7ea9ed5b94c6.png)

The native ENET C blob is untouched and not compiled for UWP C/C++. So that's a bonus. Now the real question is that will this work with Unity? Let's find out...

**Comment by SoftwareGuy** [comment] 2019-11-23 04:11
Okay, some results. I tested ENET on C# via Ignorance and the PongChamp test scene. As seen below, it is confirmed operational for LAN Clients, but LAN Host functionality does not work inside Windows UWP, at least the IL2CPP runtime. Mono might, haven't checked that out.

Here's what it looks like on my workstation:
![image](https://user-images.githubusercontent.com/1762115/69472840-ce290000-0dfa-11ea-96ab-81de0c0bdb77.png)

Does this tick the right boxes?

**Comment by Alexees** [comment] 2019-11-23 08:35
That's really cool news as at least we are not using UWP for hosting. I have not checked if ENet is dll based so my next question would be: if so, do dlls exist for x32, x64, ARM, or does it just compile?

**Comment by SoftwareGuy** [comment] 2019-11-23 09:17
ENET does require DLLs since it's written in C, unless you want to compile the blobs yourself every time there's an update to ENet-CSharp (using outdated blobs with newer revisions of the Wrapper may cause problems). I'd have to install a cross-compiler toolchain to compile for ARM64 from Visual Studio. I am not too familiar with ARM64 libraries to I'd need to look into that.

**Comment by Alexees** [comment] 2019-11-23 09:26
ARM32 would probably also do for now. Hololens 2 is the only device currently needing any of the two and is not even available for most devs at the moment.
If client on x32 and x64 is working, that's already more than hi could ask for.
How do I get my hands on it?

**Comment by SoftwareGuy** [comment] 2019-11-28 07:58
@Alexees sorry for the late response.
I have included the binaries inside the Git master branch of Ignorance; so you can git clone that repo and get the binary DLLs that way.

ARM32/ARM64 will probably require me to install the ARM cross-compiler toolchain and I really don't want to do that... I might see if I can spin up a Virtual Machine or something to prevent having toolchains all over my workstation. 😛

**Comment by Alexees** [comment] 2019-11-28 10:00
I guess that's your decision and might require a talk with the Dissonance guys as well. I have no idea if their part would run on HL2 😋
Anyways, awesome work... I'll try it as soon as I can.

**Comment by SoftwareGuy** [comment] 2019-12-03 05:41
I'll get in touch with the Dissonance guy - he's around on the Mirror discord :)

**Comment by Alexees** [comment] 2020-05-25 04:45
@SoftwareGuy how is it going? Any news on the UWP Dissonance support?

**Comment by SoftwareGuy** [comment] 2020-05-25 05:30
ENET/Ignorance works with UWP with IL2CPP. Just not in server mode.
Did you need ARM64 binaries?

I haven't tested Dissonance explicitly though. Was I supposed to test it?

**Comment by Alexees** [comment] 2020-05-25 06:03
Oh, I thought from your last comment "will get in touch with the Dissoance guy" you would have been going and would have done that (are those tenses even right :P)
I think I'll get back to you as soon as we need to integrate HL2, which of now lost importance in our project.

**Comment by SoftwareGuy** [comment] 2020-05-25 06:09
Ahh okay, so you've put the Holo Lens side of things on the backburner? That's no worries - I'll see if I can get ARM64 binaries of ENET baked as an excerise.

**Comment by SoftwareGuy** [comment] 2021-10-19 08:05
No updates as of 19th October 2021 - closing. If still required please let me know.

**Closed as completed by SoftwareGuy** 2021-10-19 08:05 UTC
Labels: enhancement
