### ISSUE TITLE
C# ENet client vs C++ ENet server

### ISSUE THREAD

**Issue by MuravyevArtem** [SoftwareGuy/ENet-CSharp#23] opened 2021-04-28 16:19 UTC
Hello!
I want to move my game from native TCP to ENet UDP. I have a C++ ENet game server and a Unity game.
I ran into an incomprehensible problem using your version of C# ENet.
I started the server and try to connect to it from the Unity through your ENet library, but the connection fails. In a Unity, when try connecting, it displays a connection timeout error. The server does not respond in any way to connection attempts.
I created an ENet client in C++ - it connects to my game server without problems and works.
Have you ever faced a similar task - connect from C# ENet client to a C++ ENet server?
I saw a post about a C++ ENet client and a C# ENet server, but there was a reaction to the connection, but I have not observed any reaction.
What could be the problem?
All code is used from the documentation - I did not add anything extra.

**Comment by SoftwareGuy** [comment] 2021-04-29 02:59
Hi there.

What platform are you targeting with the C# ENet client? Right now the repository, unless you manually compile, will only provide Windows 64Bit libraries. This is subject to change soon.

Are you using the ENet source provided in this repository? Mix and matching ENet versions is a no-no.

For the C++ part I suspect it defaults to the native CPU mode (32bit or 64bit) so that might explain why it "just works" there. I am not sure as I only know the absolute minimum of C++, I'm more of a C# guy... 😅 

Connection timeout sounds like there's a blocked port or it's bound to some address that the C# client isn't connecting to.  If you can, make a very barebones C++ ENet ping-pong server and provide me the source so I can compile and test it with ENet-C#.

**Comment by MuravyevArtem** [comment] 2021-04-29 07:13
Hello!
I use 64bit for both sides. Client on Windows 64bit and server on Debian 10 64bit.
I did some experiments today on monitoring server traffic and got the following results.

```
TCP DUMP when try to connect from C# Client:
09:37:36.645360 IP 5.251.87.110.6123 > 85.119.149.12.50130: UDP, length 52
        0x0000:  0000 0001 0006 f04b 3a26 8864 0000 0800  .......K:&.d....
        0x0010:  4500 0050 bed3 0000 7711 3cdd 05fb 576e  E..P....w.<...Wn
        0x0020:  5577 950c 17eb c3d2 003c b835 4fff 0001  Uw.......<.5O...
        0x0030:  82ff 0001 0000 ffff 0000 0500 0001 0000  ................
        0x0040:  0000 0001 0000 0000 0000 0000 0000 1388  ................
        0x0050:  0000 0002 0000 0002 544f e3b7 0000 0000  ........TO......
```

```
TCP DUMP when connecting from C++ Client:
09:38:29.336639 IP 5.251.87.110.6129 > 85.119.149.12.50130: UDP, length 52
        0x0000:  0000 0001 0006 f04b 3a26 8864 0000 0800  .......K:&.d....
        0x0010:  4500 0050 bed4 0000 7711 3cdc 05fb 576e  E..P....w.<...Wn
        0x0020:  5577 950c 17f1 c3d2 003c a717 8fff ba98  Uw.......<......
        0x0030:  82ff 0001 0000 ffff 0000 0578 0001 0000  ...........x....
        0x0040:  0000 0002 0000 0000 0000 0000 0000 1388  ................
        0x0050:  0000 0002 0000 0002 f325 5ae8 0000 0000  .........%Z.....
09:38:29.343938 IP 85.119.149.12.50130 > 5.251.87.110.6129: UDP, length 48
        0x0000:  0004 0001 0006 5065 f36e 679c 0000 0800  ......Pe.ng.....
        0x0010:  4500 004c f03e 0000 4011 4276 5577 950c  E..L.>..@.BvUw..
        0x0020:  05fb 576e c3d2 17f1 0038 4836 9000 abdf  ..Wn.....8H6....
        0x0030:  83ff 0001 0000 0101 0000 0578 0001 0000  ...........x....
        0x0040:  0000 0002 0000 0000 0000 0000 0000 1388  ................
        0x0050:  0000 0002 0000 0002 f325 5ae8            .........%Z.
09:38:29.405347 IP 5.251.87.110.6129 > 85.119.149.12.50130: UDP, length 16
        0x0000:  0000 0001 0006 f04b 3a26 8864 0000 0800  .......K:&.d....
        0x0010:  4500 002c bed5 0000 7711 3cff 05fb 576e  E..,....w.<...Wn
        0x0020:  5577 950c 17f1 c3d2 0018 5d4b 9000 badf  Uw........]K....
        0x0030:  01ff 0001 0001 abdf 85ff 0002 15d4       ..............
09:38:29.419365 IP 85.119.149.12.50130 > 5.251.87.110.6129: UDP, length 10
        0x0000:  0004 0001 0006 5065 f36e 679c 0000 0800  ......Pe.ng.....
        0x0010:  4500 0026 f04d 0000 4011 428d 5577 950c  E..&.M..@.B.Uw..
        0x0020:  05fb 576e c3d2 17f1 0012 4810 1000 01ff  ..Wn......H.....
        0x0030:  0002 0002 badf                           ......
09:38:29.811338 IP 85.119.149.12.50130 > 5.251.87.110.6129: UDP, length 16
        0x0000:  0004 0001 0006 5065 f36e 679c 0000 0800  ......Pe.ng.....
        0x0010:  4500 002c f088 0000 4011 424c 5577 950c  E..,....@.BLUw..
        0x0020:  05fb 576e c3d2 17f1 0018 4816 9000 adb3  ..Wn......H.....
        0x0030:  8aff 0002 0000 0000 0000 0000            ............
09:38:29.871624 IP 5.251.87.110.6129 > 85.119.149.12.50130: UDP, length 10
        0x0000:  0000 0001 0006 f04b 3a26 8864 0000 0800  .......K:&.d....
        0x0010:  4500 0026 bed6 0000 7711 3d04 05fb 576e  E..&....w.=...Wn
        0x0020:  5577 950c 17f1 c3d2 0012 1c63 1000 01ff  Uw.........c....
        0x0030:  0002 0002 adb3 0000 0000 9671 8914       ...........q..
09:38:30.386631 IP 85.119.149.12.50130 > 5.251.87.110.6129: UDP, length 8
        0x0000:  0004 0001 0006 5065 f36e 679c 0000 0800  ......Pe.ng.....
        0x0010:  4500 0024 f0be 0000 4011 421e 5577 950c  E..$....@.B.Uw..
        0x0020:  05fb 576e c3d2 17f1 0010 480e 9000 aff2  ..Wn......H.....
        0x0030:  85ff 0003                                ....
09:38:30.404931 IP 5.251.87.110.6129 > 85.119.149.12.50130: UDP, length 12
        0x0000:  0000 0001 0006 f04b 3a26 8864 0000 0800  .......K:&.d....
        0x0010:  4500 0028 bed7 0000 7711 3d01 05fb 576e  E..(....w.=...Wn
        0x0020:  5577 950c 17f1 c3d2 0014 084b 9000 bec7  Uw.........K....
        0x0030:  84ff 0003 0000 0000 0000 f007 96dd       ..............
09:38:30.416823 IP 85.119.149.12.50130 > 5.251.87.110.6129: UDP, length 10
        0x0000:  0004 0001 0006 5065 f36e 679c 0000 0800  ......Pe.ng.....
        0x0010:  4500 0026 f0c4 0000 4011 4216 5577 950c  E..&....@.B.Uw..
        0x0020:  05fb 576e c3d2 17f1 0012 4810 1000 01ff  ..Wn......H.....
        0x0030:  0003 0003 bec7                           ......
```

As you can see, for C++ the connection works, but for C# the connection request comes to the server, but the server does not react to it in any way.

My simple C# client code is:

```
using ENet;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ENetCSClientTest
{
    class Program
    {
        static void Main(string[] args)
        {
			ENet.Library.Initialize();

			using (Host client = new Host())
			{
				Address address = new Address();

				address.SetHost("85.119.149.12");
				address.Port = 50130;
				client.Create();

				Peer peer = client.Connect(address);

				Event netEvent;
				
				while (!Console.KeyAvailable)
				{					
					bool polled = false;

					while (!polled)
					{
						if (client.CheckEvents(out netEvent) <= 0)
						{
							if (client.Service(10000, out netEvent) <= 0)
							{
								break;
							}
							polled = true;
						}

						switch (netEvent.Type)
						{
							case EventType.None:
								break;

							case EventType.Connect:
								Console.WriteLine("Client connected to server");
								break;

							case EventType.Disconnect:
								Console.WriteLine("Client disconnected from server");
								break;

							case EventType.Timeout:
								Console.WriteLine("Client connection timeout");
								break;

							case EventType.Receive:
								Console.WriteLine($"Packet received from server - Channel ID: {netEvent.ChannelID}, Data length: {netEvent.Packet.Length}");
								netEvent.Packet.Dispose();
								break;
						}
					}
				}

				client.Flush();
			}

			ENet.Library.Deinitialize();
		}
    }
}
```

After 10 seconds, a new connection request is sent from client to server and after 30 seconds it falls off with a connection timeout error.

My simple C++ client code is (and it is work):

```
#include <enet/enet.h>
#include <stdio.h>
#include <string.h>
#include <iostream>
#include <cstdlib>

int main(int argc, char** argv)
{
    if (enet_initialize() != 0) {
        printf("Could not initialize enet.\n");
        system("pause"); 
        return 0;
    }
    atexit(enet_deinitialize);

    ENetHost* client;
    
    client = enet_host_create(NULL, 1, 2, 0, 0);

    if (client == NULL) {
        printf("Could not create client.\n");
        system("pause"); 
        return 0;
    }

    ENetAddress address;
    ENetEvent event;
    ENetPeer* peer;

    /* Connect to some.server.net:1234. */
    enet_address_set_host(&address, "85.119.149.12");
    address.port = 50130;

    /* Initiate the connection, allocating the two channels 0 and 1. */
    peer = enet_host_connect(client, &address, 2, 0);
    if (peer == NULL)
    {
        fprintf(stderr,
            "No available peers for initiating an ENet connection.\n");
        system("pause");
        exit(EXIT_FAILURE);
    }

    /* Wait up to 5 seconds for the connection attempt to succeed. */
    if (enet_host_service(client, &event, 5000) > 0 &&
        event.type == ENET_EVENT_TYPE_CONNECT)
    {
        puts("Connection to 85.119.149.12:30131 succeeded.");
        enet_host_flush(client);
    }
    else
    {
        /* Either the 5 seconds are up or a disconnect event was */
        /* received. Reset the peer in the event the 5 seconds   */
        /* had run out without any significant event.            */
        enet_peer_reset(peer);
        puts("Connection to 85.119.149.12:30131 failed.");
        exit(EXIT_FAILURE);
    }

    while (enet_host_service(client, &event, 1000) > 0)
    {
        switch (event.type)
        {
        case ENET_EVENT_TYPE_RECEIVE:
            printf("A packet of length %u containing %s was received from %x:%u on channel %u.\n",
                event.packet->dataLength,
                event.packet->data,
                event.peer->address.host,
                event.peer->address.port,
                event.channelID);
            break;
        }
    }

    enet_peer_disconnect(peer, 0);

    while (enet_host_service(client, &event, 3000) > 0)
    {
        switch (event.type)
        {
        case ENET_EVENT_TYPE_RECEIVE:
            enet_packet_destroy(event.packet);
            break;
        case ENET_EVENT_TYPE_DISCONNECT:
            puts("DISCONNECTED!");
            break;
        }
    }

    system("pause");
}
```

Sorry - the code may be ugly, but it works for tests.

**Comment by SoftwareGuy** [comment] 2021-04-29 09:00
I think you forgot to tell me where you got the native library from. 😅 

Are you compiling the version in this repository or are you using a different one? The ENet code within is very different to the original ENet, and you can't use ENet C# from here with a older/legacy ENet version.

**Comment by MuravyevArtem** [comment] 2021-04-29 09:18
Sorry, I somehow didn't think about it... Yes, I used the original library from enet.bespin.org for the server side. I thought that the protocols should be compatible... Is there a solution for such a task? Can I just add native enet header from your sources to my server directly and use it without  dependencies from compiled library on debian?

**Comment by SoftwareGuy** [comment] 2021-04-29 09:40
The protocols have changed a lot from version 1 to version 2. So there's no direct upgrade path.

The only way is to upgrade your game's ENet. This may hurt if you've already got servers and whatnot in production with a large player base, but you'll get lots of cool improvements.

If you want to compile your ENet binaries from source, you can git clone this repo and run one of the auto-build scripts in the `AutoBuild` directory. This is great if you don't trust GitHub automatic workflow compiles. It does require NET Core SDK 3.x or 5.x to run the MSBuild-powered build routines, CMake for Windows and the Windows SDK for Windows-based compiling.

However if you want to use Windows/Mac/Linux binaries, grab them from the release part of this repository. You'll get the latest and greatest. There's no malicious code in them, they are 100% reproducible from the code in this repository.

**Comment by SoftwareGuy** [comment] 2021-04-29 09:42
Sure, adding "enet_logging.h", "enet.c" and "enet.h" to your project *should* work fine. There shouldn't be any dependencies attached to them.

**Comment by MuravyevArtem** [comment] 2021-04-29 09:46
Okay! Thank you very much for your help in understanding the situation! I will try to implement the variant with your sources. I will let you know about the results. Excuse for troubling!

**Comment by MuravyevArtem** [comment] 2021-04-29 11:32
Sorry again. I managed to edit the server and now everything works on a 64bit platform. But the client must be running on 32bit version. What needs to be changed to compile a 32bit library? I tried different options - through the console, through the visual studio - but it always produces a 64bit library. Or is it not possible at the moment?

**Comment by SoftwareGuy** [comment] 2021-04-29 12:22
Out of the box, the MSBuild configuration uses 64Bit IIRC. I think to work around this you manually had to use CMake GUI on Windows, point it to the ENet source, then hit configure and make sure you selected the MSVC toolchain that didn't say "x64" in it.

I can't remember the exact steps but if you can give me a day (it's 10:21 PM here) I'll give you a run-down of the whole process once I can successfully spit out a 32Bit library.

**Comment by MuravyevArtem** [comment] 2021-04-29 12:41
Thanks for the tip on cmake gui. Through it, I configure the native library on the win32 platform and then build it through the visual studio. Everything worked out - the resulting dll library runs on a 32-bit platform in Unity. Thanks a lot again!!!

**Comment by SoftwareGuy** [comment] 2021-04-29 12:45
Oh sweet, that worked? Excellent, great to hear! 😀

**Comment by MuravyevArtem** [comment] 2021-05-01 12:31
Hello again! Is it possible to disable the enet-debug.log?

**Comment by SoftwareGuy** [comment] 2021-05-01 12:36
Make sure ENET_DEBUG is not defined, or set to 0/FALSE.

**Comment by valkyrienyanko** [comment] 2021-08-03 21:37
Hello, I've also decided to create a ENet C++ server and am trying to connect a ENet C# client to the server. I don't fully understand everything that has been discussed above. Could someone please help me with this?

Server Repo - Server.cpp <https://github.com/Kittens-Rise-Up/server-cpp/blob/main/server/src/Server/Server.cpp>
Client Repo - Client.cs <https://github.com/Kittens-Rise-Up/client/blob/main/Assets/Scripts/Netcode/ENetClient.cs> (m_Port is actually 1234 I just never commit my changes for that)

**Comment by SoftwareGuy** [comment] 2021-08-04 04:41
@valkyrienyanko To recap, what was stated above:

1) If you use the pre-compiled ENet binaries I compile, they are for 64Bit only. That means you will have to compile your server application code as 64Bit. Trying to use the 64Bit `enet.dll` file or `libenet.so` with a 32Bit application **will fail** and likely crash your application, if not throw an unhandled exception. 

If you are designing a server to run on 32Bit devices, then you will need to compile ENet yourself, targeting 32bit CPU type. Alternatively, you could bake ENet into your application to avoid having to carry around another dependency, but that'll require some work on your side.

2) When compiling, to disable the ENET Debug Log file make sure `ENET_DEBUG` is not present in the build defines or set `ENET_DEBUG` to `FALSE` or 0.

Without further info on what exactly you need help with specifically, I am limited with what I can help you with.

**Comment by MuravyevArtem** [comment] 2021-08-04 05:26
Hello! Also keep in mind - on the server side, you must use the sources from this version of the library (https://github.com/SoftwareGuy/ENet-CSharp/blob/master/Source/Native/enet.h). The sources from the official site http://enet.bespin.org/ will not work.

**Comment by valkyrienyanko** [comment] 2022-01-02 08:43
I'm having troubles setting this up. I grabbed `enet.h` `enet.c` `enet_logging.h` from https://github.com/SoftwareGuy/ENet-CSharp/blob/master/Source and put them in my project in `vendor/enet`

As you can see I'm using the tutorial code from http://enet.bespin.org/ but some of the code has changed in this version and I'm not sure what to do to fix it
![image](https://user-images.githubusercontent.com/6277739/147870519-67448372-861e-4ad8-bc8f-de04964bc864.png)
![image](https://user-images.githubusercontent.com/6277739/147870711-b19244fb-2d31-497e-994a-a9ca222e9ca2.png)
![image](https://user-images.githubusercontent.com/6277739/147870728-45ebfcad-3202-4287-9121-c89b1c142075.png)


This is what my premake looks like
![image](https://user-images.githubusercontent.com/6277739/147870589-678102c9-e575-4d36-846b-9f132fed8adc.png)

This is what my folder structure looks like
![image](https://user-images.githubusercontent.com/6277739/147870613-422db948-2d95-4738-b811-e7e09d815a89.png)

Build errors
![image](https://user-images.githubusercontent.com/6277739/147870641-831a1a91-dfec-44a3-93c0-d104752ba9c2.png)

Here is my server repo https://github.com/Raccoons-Rise-Up/server-cpp (the repo still uses enet from http://enet.bespin.org/ I just have not pushed a commit of my latest changes so just ignore that)

**Comment by SoftwareGuy** [comment] 2022-01-02 09:26
Please don't mix and match anything from bespin and this repository. It's likely to be outdated or incompatible with the API in this repository.

If you look at the ENet-CSharp bindings you will find references to the native calls, that would reference things like enet_address_set_host, etc.

**Comment by SoftwareGuy** [comment] 2022-05-22 04:41
Closing this due to age of the support ticket.

**Closed as completed by SoftwareGuy** 2022-05-22 04:41 UTC
